# TO use this Makefile to build the code in this directory, install the arduino-mk package
# (on debian based dsitros)

BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM0
ARDUINO_LIBS = HCARDU0023_LiquidCrystal_I2C_V2_1 SoftwareSerial Wire SPI Ethernet PubSubClient rfid EEPROM
USER_LIB_PATH := $(realpath ../Libraries)

include $(ARDMK_DIR)/Arduino.mk


