# TO use this Makefile to build the code in this directory, install the arduino-mk package
# (on debian based dsitros)
BOARD_TAG = uno
ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_LIBS = PubSubClient EEPROM Wire SPI Ethernet RDM880
USER_LIB_PATH := $(realpath ../Libraries)

include $(ARDMK_DIR)/Arduino.mk
