# TO use this Makefile to build the code in this directory, install the arduino-mk package
# (on debian based dsitros)

BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_LIBS = LiquidCrystal_I2C Wire SPI Ethernet PubSubClient MFRC522
USER_LIB_PATH := $(realpath ../libraries)

include $(ARDMK_DIR)/Arduino.mk